### ISSUE TITLE
I met this error when run your ipynb source.

### ISSUE THREAD

**Issue by bemoregt** [Sayan98/deepcosegmentation.pytorch#1]
Hi, @say4n @sayan91 

I met this error when run your ipynb source.

No such file or directory: '/home/kerbal/coseg_model_best.pth'

What's wrong to me?
How can I download that pth model ?

Thanks.
Best,
@bemoregt.

**Comment by say4n** [comment]
Hi @bemoregt, you need to run [`src/train.py`](https://github.com/say4n/deepcosegmentation.pytorch/blob/master/src/train.py) before you can use the notebook. The training script will generate checkpoints for you. You may run `python3 src/train.py --help` for more information on the supported arguments.
