### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by bemoregt** [Sayan98/deepcosegmentation.pytorch#2]
Hi, @say4n @sayan91 

How can I get the dataset for train this segnet?

Thanks.
Best,
@bemoregt.

**Comment by say4n** [comment]
Hi, @bemoregt as far as I can recall, we used iCoseg, Pascal VOC etc. Check [these](https://github.com/say4n/deepcosegmentation.pytorch/blob/73098eed7c097fa0add3f0a6907df36a4e9a5d85/src/train.py#L94) lines out.

Also, my apologies for getting back so late! :)
